### PR TITLE
Fix dead loop.

### PR DESCRIPTION
**Pull request by zoumi**
rng.gen_ascii_chars() will continuously generate random ascii characters, if we don't take some,it will loop for ever.

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks!

**Comment by untitaker** [comment]
released 0.6.4

**Comment by zoumi** [comment]
I was suffer with another bug...
iron-sessionstorage set this in header

    Set-Cookie:iron_session_id=5gO7jsfBy0CTFEUcT3zqGFI3JyhJY9HYTV3zexHh
But my browser doesn't accept it. There should be an ";" at the end???
And where is httponly?

**Comment by untitaker** [comment]
>There should be an ";" at the end???

Not necessarily I think, see https://tools.ietf.org/html/rfc6265#section-4.1.1 So if I have no params it should be fine.

httponly is a good idea, feel free to make a PR right here: https://github.com/iron/iron-sessionstorage/blob/7e17a70b517a8d7f51dded59c3984c2b3e318f00/src/backends/redis.rs#L85

**Comment by zoumi** [comment]
Sorry, the fact is my broswer has accept the cookie, but iron-sessionstorage still put "Set-Cookie" everytime.

**Comment by untitaker** [comment]
Could you try master? I pushed https://github.com/iron/iron-sessionstorage/commit/66a1344fda449af01c3ec00471943b335fd9d0ec

**Comment by zoumi** [comment]
@untitaker It didn't work when there is no iron_session_id in req's header.

**Comment by untitaker** [comment]
What exactly doesn't work?

**Comment by zoumi** [comment]
After iron-sessionstorage  set iron_session_id in my broswer, I clear my broswer's cookies.
In the next req, iron-sessionstorage still doesn't set anything.

**Comment by zoumi** [comment]
In my test codes, I only chain iron-sessionstorage, didn't use any struct like "Login" which you put in the login example.
And, I'm not good at English.Reading is much better than writing...

**Comment by untitaker** [comment]
>In the next req, iron-sessionstorage still doesn't set anything.

If you don't set anything in the session, it doesn't have to set a cookie.

Could you give me a small code example and describe the expected behavior?

**Comment by zoumi** [comment]
> If you don't set anything in the session, it doesn't have to set a cookie.

I guess you are right.I will test it later.
I'm testing redis-backend, so the code is all the mess.It will be hard for you to make it work.
So, you didn't do any test before publish this crate?

**Pull request merged**
